import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Bot, Check, Loader2, LocateFixed, RotateCcw } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export default function BetaCheckDialog({open,onOpenChange,issues,onApply,onLocate,onIgnore,onAiCheck,aiRunning,onUndo,canUndo}) {
  const [values,setValues]=useState({});
  const [remember,setRemember]=useState({});
  useEffect(()=>{if(open)setValues(Object.fromEntries((issues||[]).map(item=>[item.id,item.replacement||""])));},[open,issues]);
  const groups=useMemo(()=>Object.values((issues||[]).reduce((acc,item)=>{const key=`${item.label}\u0001${item.value}\u0001${item.replacement||""}`;(acc[key]||={key,label:item.label,value:item.value,replacement:item.replacement||"",safe:item.safe,items:[]}).items.push(item);return acc;},{})),[issues]);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl max-h-[88vh] overflow-y-auto rounded-2xl">
    <DialogHeader><DialogTitle className="flex items-center gap-2 text-fuchsia-700">✍️ Beta câu văn theo chương</DialogTitle></DialogHeader>
    <div className="rounded-xl border border-fuchsia-100 bg-fuchsia-50/50 p-3 text-xs text-slate-600">Code đã quét trước. AI chỉ nhận tối đa 16 câu nghi vấn có ngữ cảnh, chỉ đề xuất và không tự sửa.</div>
    <div className="flex flex-wrap gap-2"><button disabled={aiRunning||!issues?.length} onClick={onAiCheck} className="inline-flex items-center gap-1.5 rounded-xl bg-fuchsia-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">{aiRunning?<Loader2 className="h-4 w-4 animate-spin"/>:<Bot className="h-4 w-4"/>} AI xem câu khó</button>{canUndo&&<button onClick={onUndo} className="inline-flex items-center gap-1.5 rounded-xl border px-3 py-2 text-xs"><RotateCcw className="h-4 w-4"/>Hoàn tác</button>}</div>
    <div className="space-y-3">{groups.map(group=><article key={group.key} className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex gap-2"><AlertTriangle className={`mt-0.5 h-4 w-4 shrink-0 ${group.safe?"text-emerald-500":"text-amber-500"}`}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b>{group.label}</b><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px]">{group.items.length} vị trí</span>{group.safe&&<span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] text-emerald-700">Có thể sửa nhanh</span>}</div><p className="mt-1 text-xs text-slate-500">{group.items[0].detail}</p></div></div>
      <div className="mt-2 space-y-1.5">{group.items.slice(0,4).map(item=><button key={item.id} onClick={()=>onLocate(item)} className="block w-full rounded-lg bg-slate-50 px-2.5 py-2 text-left text-xs text-slate-600"><span className="mr-1 text-[10px] text-fuchsia-600">Dòng {item.line}</span>…{item.context}…</button>)}</div>
      <div className="mt-3 flex flex-wrap items-center gap-2"><input value={values[group.items[0].id]??group.replacement} onChange={e=>setValues({...values,[group.items[0].id]:e.target.value})} placeholder="Cách sửa…" className="min-w-40 flex-1 rounded-lg border px-2.5 py-1.5 text-xs"/><label className="flex items-center gap-1 text-[10px] text-slate-500"><input type="checkbox" checked={Boolean(remember[group.key])} onChange={e=>setRemember({...remember,[group.key]:e.target.checked})}/>Ghi nhớ</label><button onClick={()=>onIgnore(group,Boolean(remember[group.key]))} className="px-2 py-1 text-xs text-slate-400">Bỏ qua</button><button disabled={!group.safe&&!String(values[group.items[0].id]??group.replacement).trim()} onClick={()=>onApply(group.items,values[group.items[0].id]??group.replacement,Boolean(remember[group.key]))} className="inline-flex items-center gap-1 rounded-lg bg-fuchsia-600 px-3 py-1.5 text-xs font-medium text-white disabled:opacity-40"><Check className="h-3.5 w-3.5"/>Áp dụng {group.items.length>1?group.items.length:""}</button><button onClick={()=>onLocate(group.items[0])} className="rounded-lg border px-2 py-1.5 text-xs"><LocateFixed className="h-3.5 w-3.5"/></button></div>
    </article>)}</div>
    {!groups.length&&<div className="rounded-xl bg-emerald-50 p-5 text-center text-emerald-700">Không phát hiện lỗi Beta bằng code.</div>}
  </DialogContent></Dialog>;
}
