import { useEffect, useState } from "react";
import { Bot, ExternalLink, Loader2, Plus, SearchCheck, Trash2, Zap } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";

const defaults={longSentence:180,longParagraph:900,rules:[],ignored:[]};
export default function StoryBetaDialog({open,onOpenChange,settings,report,running,onSaveSettings,onScan,onBulkReplace,onIgnore,onOpenChapter,pending=[],onApplyAllSafe,onStartAiBatch,aiBatchPendingCount=0}) {
  const [form,setForm]=useState(defaults),[replacement,setReplacement]=useState({}),[view,setView]=useState("issues"),[selected,setSelected]=useState({});
  useEffect(()=>{if(open)setForm({...defaults,...settings});},[open,settings]);
  useEffect(()=>{if(report){setReplacement(Object.fromEntries((report.groups||[]).map(g=>[g.key,g.replacement||""])));setSelected(Object.fromEntries((report.groups||[]).map(g=>[g.key,new Set(g.locations.map(loc=>loc.id))])));}},[report]);
  const toggle=(key,id)=>setSelected(current=>{const next=new Set(current[key]||[]);if(next.has(id))next.delete(id);else next.add(id);return{...current,[key]:next};});
  const addRule=()=>setForm({...form,rules:[...(form.rules||[]),{find:"",replace:""}]});
  const safeOccurrences=(report?.groups||[]).filter(g=>g.safe).reduce((sum,g)=>sum+(g.locations?.length||0),0);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto rounded-2xl"><DialogHeader><DialogTitle className="text-fuchsia-700">✍️ Trung tâm Beta toàn truyện</DialogTitle></DialogHeader>
    <div className="space-y-3 rounded-xl border border-fuchsia-100 bg-fuchsia-50/40 p-3"><div className="grid grid-cols-2 gap-2"><label className="text-xs">Cảnh báo câu dài từ<input type="number" value={form.longSentence} onChange={e=>setForm({...form,longSentence:e.target.value})} className="mt-1 w-full rounded-lg border bg-white px-2 py-1.5"/></label><label className="text-xs">Cảnh báo đoạn dài từ<input type="number" value={form.longParagraph} onChange={e=>setForm({...form,longParagraph:e.target.value})} className="mt-1 w-full rounded-lg border bg-white px-2 py-1.5"/></label></div>
      <div><div className="flex justify-between text-xs font-semibold"><span>Quy tắc đã học: trước → sau</span><button onClick={addRule} className="text-fuchsia-600"><Plus className="inline h-3.5 w-3.5"/> Thêm</button></div><div className="mt-2 space-y-2">{(form.rules||[]).map((rule,index)=><div key={index} className="flex gap-2"><input value={rule.find} onChange={e=>setForm({...form,rules:form.rules.map((r,i)=>i===index?{...r,find:e.target.value}:r)})} placeholder="Cụm cần cảnh báo" className="min-w-0 flex-1 rounded-lg border px-2 py-1.5"/><input value={rule.replace} onChange={e=>setForm({...form,rules:form.rules.map((r,i)=>i===index?{...r,replace:e.target.value}:r)})} placeholder="Cách sửa" className="min-w-0 flex-1 rounded-lg border px-2 py-1.5"/><button onClick={()=>setForm({...form,rules:form.rules.filter((_,i)=>i!==index)})}><Trash2 className="h-4 w-4 text-red-400"/></button></div>)}</div></div>
      <div className="flex flex-wrap justify-end gap-2"><Button variant="outline" onClick={()=>onSaveSettings(form)}>Lưu quy tắc</Button><Button variant="outline" onClick={onStartAiBatch} className="border-fuchsia-200 text-fuchsia-700 hover:bg-fuchsia-50"><Bot className="mr-2 h-4 w-4"/>AI Beta hàng loạt{aiBatchPendingCount>0?` · ${aiBatchPendingCount} chờ duyệt`:""}</Button><Button disabled={running} onClick={async()=>{await onSaveSettings(form);await onScan(form);}} className="bg-fuchsia-600 hover:bg-fuchsia-700">{running?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<SearchCheck className="mr-2 h-4 w-4"/>}Quét Beta toàn truyện</Button></div></div>
    {report&&<><div className="flex flex-wrap items-center justify-between gap-2">
      <div className="flex gap-1 rounded-xl bg-slate-100 p-1 flex-1 min-w-0"><button onClick={()=>setView("issues")} className={`flex-1 rounded-lg px-3 py-2 text-xs font-semibold ${view==="issues"?"bg-white text-fuchsia-700 shadow-sm":"text-slate-500"}`}>Lỗi tổng thể · {report.issueCount}</button><button onClick={()=>setView("next")} className={`flex-1 rounded-lg px-3 py-2 text-xs font-semibold ${view==="next"?"bg-white text-fuchsia-700 shadow-sm":"text-slate-500"}`}>Chương cần Beta · {pending.length}</button></div>
      {safeOccurrences>0&&<Button size="sm" disabled={running} onClick={()=>onApplyAllSafe(form)} className="bg-emerald-600 hover:bg-emerald-700 shrink-0"><Zap className="mr-1.5 h-3.5 w-3.5"/>Sửa {safeOccurrences} vị trí an toàn</Button>}
    </div>
      {view==="issues"?<div className="space-y-3">{(report.groups||[]).map(group=>{const chosen=selected[group.key]||new Set();return <article key={group.key} className="overflow-hidden rounded-xl border bg-white p-3"><div className="flex flex-wrap items-center gap-2"><b className="min-w-0">{group.label}</b><span className="shrink-0 rounded-full bg-slate-100 px-2 py-0.5 text-[10px]">{group.count} lần · {group.chapterCount} chương</span>{group.safe&&<span className="shrink-0 rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] text-emerald-700">Sửa hàng loạt được</span>}<Button size="sm" disabled={running||!group.safe||!chosen.size} onClick={()=>onBulkReplace(group,replacement[group.key]??group.replacement,form,[...chosen])} className="ml-auto shrink-0 bg-emerald-600 hover:bg-emerald-700">Thay {chosen.size}/{group.count} vị trí</Button></div><div className="mt-2 flex min-w-0 gap-2"><code className="max-w-[45%] truncate rounded bg-red-50 px-2 py-1 text-xs text-red-700">{group.value}</code><input value={replacement[group.key]??""} onChange={e=>setReplacement({...replacement,[group.key]:e.target.value})} placeholder="Cách thay…" className="min-w-0 flex-1 rounded-lg border px-2 py-1 text-xs"/></div><div className="mt-2 max-h-52 space-y-1 overflow-x-hidden overflow-y-auto">{group.locations.map(loc=><div key={loc.id} className={`flex min-w-0 gap-2 rounded-lg p-2 text-xs ${chosen.has(loc.id)?"bg-fuchsia-50":"bg-slate-50 opacity-60"}`}><input type="checkbox" checked={chosen.has(loc.id)} onChange={()=>toggle(group.key,loc.id)} className="shrink-0 accent-fuchsia-600"/><button onClick={()=>onOpenChapter(loc.chapterId)} className="min-w-0 flex-1 text-left"><b className="text-fuchsia-600">{loc.chapter_order}. {loc.chapterTitle}</b> · dòng {loc.line}<span className="block truncate text-slate-500">{loc.context}</span></button></div>)}</div><div className="mt-2 flex flex-wrap justify-end gap-2"><button onClick={()=>onIgnore(group,form,true)} className="text-xs text-slate-400">Bỏ qua và ghi nhớ</button><Button size="sm" variant="outline" onClick={()=>onOpenChapter(group.locations[0]?.chapterId)}><ExternalLink className="mr-1 h-3.5 w-3.5"/>Xem kỹ</Button></div></article>})}</div>:<div className="space-y-2">{pending.map(ch=><button key={ch.id} onClick={()=>onOpenChapter(ch.id)} className="flex w-full items-center rounded-xl border bg-white p-3 text-left"><span className="min-w-0 flex-1 truncate"><b>{ch.chapter_order}. {ch.title}</b><small className="block text-slate-400">Chưa Beta hoặc nội dung/quy tắc đã thay đổi</small></span><ExternalLink className="h-4 w-4 text-slate-300"/></button>)}</div>}</>}
  </DialogContent></Dialog>;
}
