import { AlertTriangle, ExternalLink, Loader2, SearchCheck, ShieldCheck } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';

export default function PronounInventoryDialog({ open, onOpenChange, report, running, onScan, onUsePair, onOpenOccurrence }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto cute-scrollbar">
    <DialogHeader><DialogTitle className="flex items-center gap-2 text-violet-700"><SearchCheck className="h-5 w-5"/>Bản đồ xưng hô toàn truyện</DialogTitle><DialogDescription>Quét bằng luật, không dùng AI và không tự thay đổi Ma trận. Chỉ những câu có dấu hiệu người nói đủ rõ mới được gán tên.</DialogDescription></DialogHeader>
    <button type="button" onClick={onScan} disabled={running} className="flex w-full items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{running?<Loader2 className="h-4 w-4 animate-spin"/>:<SearchCheck className="h-4 w-4"/>}{running?'Đang quét Bản edit…':'Quét lại toàn truyện'}</button>
    {report && <><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[[report.chapterCount,'Chương đã quét'],[report.quoteCount,'Câu thoại'],[report.groups.length,'Nhóm xưng hô'],[report.unresolvedQuotes,'Thoại chưa rõ người nói']].map(([value,label])=><div key={label} className="rounded-xl bg-slate-50 p-3 text-center"><b className="block text-lg text-slate-800">{value}</b><span className="text-xs text-slate-500">{label}</span></div>)}</div>
      <div className="space-y-3">{report.groups.map(group=><section key={group.key} className={`rounded-2xl border p-3 ${group.unexpected?'border-amber-300 bg-amber-50/50':'border-slate-200 bg-white'}`}>
        <div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold text-slate-800">{group.speaker||'Chưa rõ người nói'} → {group.listener||'Chưa rõ người nghe'}</h3><p className="text-xs text-slate-500">{group.quoteCount} lượt thoại · {group.occurrences.length} vị trí xưng hô được lưu mẫu</p></div>{group.speaker&&group.listener&&<button type="button" onClick={()=>onUsePair(group)} className="rounded-lg border border-violet-200 bg-white px-2.5 py-1.5 text-xs font-semibold text-violet-700 hover:bg-violet-50">Dùng cặp này trong biểu mẫu</button>}</div>
        {group.rule?<p className="mt-2 flex items-center gap-1 text-xs font-medium text-emerald-700"><ShieldCheck className="h-3.5 w-3.5"/>Ma trận hiện có: xưng “{group.rule.self_word}” — gọi “{group.rule.target_word}”</p>:<p className="mt-2 text-xs font-medium text-slate-500">Chưa có quy tắc cụ thể cho cặp này.</p>}
        <div className="mt-2 flex flex-wrap gap-1.5">{Object.entries(group.terms).sort((a,b)=>b[1]-a[1]).map(([term,count])=>{const allowed=group.rule&&[group.rule.self_word,group.rule.target_word].some(value=>String(value).toLocaleLowerCase('vi')===term.toLocaleLowerCase('vi'));return <span key={term} className={`rounded-full px-2 py-1 text-xs font-medium ${group.rule&&!allowed?'bg-amber-100 text-amber-800':'bg-violet-50 text-violet-700'}`}>{term} · {count}</span>})}</div>
        {!!group.unexpected&&<p className="mt-2 flex items-center gap-1 text-xs font-semibold text-amber-800"><AlertTriangle className="h-3.5 w-3.5"/>{group.unexpected} lượt dùng từ nằm ngoài cặp xưng hô đã quy định — cần xem lại.</p>}
        {!!group.occurrences.length&&<details className="mt-2"><summary className="cursor-pointer text-xs font-medium text-slate-600">Xem vị trí xuất hiện</summary><div className="mt-2 max-h-48 space-y-1 overflow-y-auto">{group.occurrences.map((item,index)=><button key={`${item.chapterId}:${item.start}:${index}`} type="button" onClick={()=>onOpenOccurrence(item)} className="flex w-full items-start gap-2 rounded-lg bg-slate-50 p-2 text-left text-xs hover:bg-violet-50"><span className="min-w-0 flex-1"><b>{item.chapterTitle}</b> · dòng {item.line}<span className="block truncate text-slate-500">…{item.context}…</span></span><ExternalLink className="h-3.5 w-3.5 shrink-0 text-slate-400"/></button>)}</div></details>}
      </section>)}{!report.groups.length&&<div className="rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">Chưa tìm thấy từ xưng hô trong lời thoại có dấu ngoặc kép.</div>}</div></>}
  </DialogContent></Dialog>;
}
