import { useCallback, useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { AlignCenter, AlignLeft, AlignRight, ArrowDown, ArrowLeft, ArrowUp, Bold, Brush, Copy, Download, Eye, EyeOff, FolderOpen, ImagePlus, Italic, Palette, Plus, Redo2, Save, Trash2, Type, Undo2, Upload, ZoomIn, ZoomOut } from "lucide-react";
import { toast } from "sonner";

const W = 1200, H = 1800;
const FORMATS = [
  { id: "book", name: "Bìa truyện dọc", width: 1200, height: 1800, hint: "Tỷ lệ 2:3" },
  { id: "youtube", name: "Thumbnail YouTube", width: 1280, height: 720, hint: "Tỷ lệ 16:9" },
  { id: "channel", name: "Banner kênh YouTube", width: 2560, height: 1440, hint: "Tỷ lệ 16:9" },
];
const CURATED_FONTS = [
  ["Fz Giao Long", "fz-giao-long.ttf"], ["Fz Đức Thủy", "fz-duc-thuy.ttf"], ["Fz Bút Bi", "fz-but-bi.ttf"], ["Fz Chữ Ký", "fz-signature.ttf"],
  ["HL Ông Đồ", "hl-ong-do.ttf"], ["HL Thư Pháp 1", "hl-thu-phap-1.ttf"], ["HL Thư Pháp 2", "hl-thu-phap-2.ttf"], ["HL Thư Pháp 5", "hl-thu-phap-5.ttf"], ["HL Brush 2", "hl-brush-2.ttf"], ["HL Brush 3", "hl-brush-3.ttf"], ["HL Giọt Mực", "hl-giot-muc.ttf"], ["HL Nét Bút", "hl-net-but.ttf"], ["HL Đại Tự", "hl-thu-phap-dai.ttf"], ["HL Mạnh Mẽ", "hl-thu-phap-manh.ttf"],
  ["Quảng Ninh Đại", "quang-ninh-dai.ttf"], ["Quảng Ninh Đại 1B", "quang-ninh-dai-1b.ttf"], ["Quảng Ninh Ngắn", "quang-ninh-ngan.ttf"], ["Thư Pháp Thành Công", "thu-phap-xuan.ttf"], ["NT Akashii", "nt-akashii.ttf"], ["TMC Ông Đồ", "tmc-ong-do.ttf"], ["UTM Thiên An", "utm-thien-an.ttf"],
  ...Array.from({ length: 12 }, (_, i) => [`Hải Yến ${i + 1}`, `hy-thu-phap-${i + 1}.otf`]),
];
const ARCHIVE_FONTS = [
  ["HL Thư Pháp 4E", "archive-01.ttf"], ["VNI Bút Lông", "archive-02.ttf"], ["VN Briquet", "archive-03.ttf"], ["VNI Disney", "archive-04.ttf"], ["VNI Dịu Dàng", "archive-05.ttf"], ["VNI HL Thư Pháp", "archive-06.ttf"], ["VNI Thư Pháp", "archive-07.ttf"], ["VNI Bay Bướm", "archive-08.ttf"], ["VNI HL Thư Pháp 2", "archive-09.ttf"], ["VNI Matisse", "archive-10.ttf"], ["VNI Nét Bút", "archive-11.ttf"], ["VNI Slogan", "archive-12.ttf"], ["VNI Thư Pháp 2", "archive-13.ttf"], ["VNI Thư Pháp 3", "archive-14.ttf"], ["VNI Thư Pháp Fan", "archive-15.ttf"], ["VNI Truck", "archive-16.ttf"], ["VNI Viết Tay", "archive-17.ttf"], ["VNI Thư Pháp 01", "archive-18.ttf"], ["VNI Thanh Cao", "archive-19.ttf"], ["VNI Thư Pháp 2B", "archive-20.ttf"], ["VNI Ông Đồ HL", "archive-21.ttf"],
];
const LOCAL_FONTS = [...CURATED_FONTS, ...ARCHIVE_FONTS];
const FONT_FILES = Object.fromEntries(LOCAL_FONTS);
const FONTS = [...LOCAL_FONTS.map(([name]) => name), "Georgia", "Times New Roman", "Palatino Linotype", "Segoe Script", "Arial"];
const PRESETS = [
  { name: "Giao Long", style: { font: "Fz Giao Long", color: "#f6d784", stroke: "#341208", shadow: "#000000", shadowBlur: 24, strokeWidth: 3, size: 146, weight: 400, spacing: 1 } },
  { name: "Đức Thủy", style: { font: "Fz Đức Thủy", color: "#fff4de", stroke: "#5b1721", shadow: "#21050a", shadowBlur: 22, strokeWidth: 2, size: 150, weight: 400, spacing: 1 } },
  { name: "Ông Đồ", style: { font: "HL Ông Đồ", color: "#edc368", stroke: "#361307", shadow: "#000000", shadowBlur: 20, strokeWidth: 3, size: 152, weight: 400, spacing: 2 } },
  { name: "Thiên An", style: { font: "UTM Thiên An", color: "#fff6e3", stroke: "#3f1922", shadow: "#17080d", shadowBlur: 25, strokeWidth: 2, size: 150, weight: 400, spacing: 1 } },
  { name: "Huyền huyễn", style: { font: "HL Đại Tự", color: "#f8e7b0", stroke: "#341709", shadow: "#000000", shadowBlur: 22, strokeWidth: 4, size: 124, weight: 700, spacing: 8 } },
  { name: "Ngôn tình", style: { font: "Hải Yến 3", color: "#fff7fb", stroke: "#6b2349", shadow: "#3b0d2a", shadowBlur: 20, strokeWidth: 3, size: 118, weight: 700, spacing: 3 } },
  { name: "Thư pháp Việt", style: { font: "Thư Pháp Thành Công", color: "#f5d06f", stroke: "#4a1708", shadow: "#160704", shadowBlur: 16, strokeWidth: 3, size: 148, weight: 700, spacing: 1 } },
  { name: "Bay bổng", style: { font: "Fz Chữ Ký", color: "#fff4dc", stroke: "#6d2735", shadow: "#25070f", shadowBlur: 24, strokeWidth: 2, size: 156, weight: 400, spacing: 2 } },
  { name: "Cổ phong", style: { font: "Quảng Ninh Đại", color: "#ead19a", stroke: "#311b11", shadow: "#000000", shadowBlur: 20, strokeWidth: 4, size: 136, weight: 700, spacing: 7 } },
  { name: "Trinh thám", style: { font: "NT Akashii", color: "#f3f0e9", stroke: "#111111", shadow: "#000000", shadowBlur: 12, strokeWidth: 5, size: 112, weight: 800, spacing: 12 } },
];
const uid = () => globalThis.crypto?.randomUUID?.() || `cover-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const makeLayer = (extra = {}, dimensions = { width: W, height: H }) => ({ id: uid(), text: "TÊN TRUYỆN", x: dimensions.width / 2, y: dimensions.height * .18, font: "Fz Giao Long", size: Math.round(dimensions.height * .07), color: "#fff8e8", weight: 700, italic: false, align: "center", opacity: 1, rotation: 0, vertical: false, spacing: 4, lineHeight: 1.08, stroke: "#231006", strokeWidth: 3, shadow: "#000000", shadowBlur: 18, shadowX: 5, shadowY: 8, maxWidth: dimensions.width * .82, visible: true, ...extra });
const rgba = (hex, a) => { const v = parseInt(hex.slice(1), 16); return `rgba(${v >> 16},${v >> 8 & 255},${v & 255},${a})`; };
const openDesignDB = () => new Promise((resolve, reject) => { const request = indexedDB.open("cover-studio", 1); request.onupgradeneeded = () => request.result.createObjectStore("projects", { keyPath: "id" }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
const projectStore = async (mode, action) => { const db = await openDesignDB(); return new Promise((resolve, reject) => { const tx = db.transaction("projects", mode), request = action(tx.objectStore("projects")); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); tx.oncomplete = () => db.close(); }); };

function linesFor(ctx, text, max, spacing) {
  const result = [];
  text.split("\n").forEach(p => { let line = ""; p.split(/\s+/).forEach(word => { const test = line ? `${line} ${word}` : word; if (ctx.measureText(test).width + Math.max(0, test.length - 1) * spacing > max && line) { result.push(line); line = word; } else line = test; }); result.push(line); });
  return result;
}
function drawLetters(ctx, text, x, y, spacing, align) {
  if (!spacing || text.length < 2) { if (ctx.lineWidth) ctx.strokeText(text, x, y); ctx.fillText(text, x, y); return; }
  const widths = [...text].map(c => ctx.measureText(c).width), total = widths.reduce((a, b) => a + b, 0) + spacing * (text.length - 1);
  let cursor = align === "center" ? x - total / 2 : align === "right" ? x - total : x;
  ctx.textAlign = "left"; [...text].forEach((c, i) => { if (ctx.lineWidth) ctx.strokeText(c, cursor, y); ctx.fillText(c, cursor, y); cursor += widths[i] + spacing; });
}

export default function CoverDesigner() {
  const navigate = useNavigate(), canvasRef = useRef(), imageInput = useRef(), fontInput = useRef(), textInput = useRef(), imageRef = useRef(), editedImage = useRef(), healBrush = useRef(), eraseHistory = useRef([]), loadedFonts = useRef(new Map()), dirtyProject = useRef(false), drag = useRef();
  const [formatId, setFormatId] = useState("book");
  const format = FORMATS.find(item => item.id === formatId) || FORMATS[0], W = format.width, H = format.height;
  const [layers, setLayers] = useState(() => [makeLayer(), makeLayer({ text: "Tác giả", y: 1560, size: 48, weight: 500, spacing: 8, strokeWidth: 0, shadowBlur: 8 })]);
  const [selectedId, setSelectedId] = useState(null), [background, setBackground] = useState(null), [shade, setShade] = useState(.12), [shadeColor, setShadeColor] = useState("#000000"), [zoom, setZoom] = useState(.36), [customFonts, setCustomFonts] = useState([]), [history, setHistory] = useState([]), [future, setFuture] = useState([]), [eraseMode, setEraseMode] = useState(false), [brushSize, setBrushSize] = useState(64), [sampleSide, setSampleSide] = useState("above"), [imageVersion, setImageVersion] = useState(0), [canUndoErase, setCanUndoErase] = useState(false);
  const [guides, setGuides] = useState({ x: false, y: false }), [showSafeZone, setShowSafeZone] = useState(true), [savedAt, setSavedAt] = useState(null), [storageReady, setStorageReady] = useState(false), [hasSavedProject, setHasSavedProject] = useState(false);
  const [bgZoom, setBgZoom] = useState(1), [bgX, setBgX] = useState(0), [bgY, setBgY] = useState(0), [bgBrightness, setBgBrightness] = useState(100), [bgContrast, setBgContrast] = useState(100);
  const selected = layers.find(x => x.id === selectedId);
  const commit = useCallback(update => { dirtyProject.current = true; setLayers(current => { const next = typeof update === "function" ? update(current) : update; setHistory(h => [...h.slice(-29), current]); setFuture([]); return next; }); }, []);
  const update = useCallback((patch, remember = true) => { dirtyProject.current = true; const fn = all => all.map(x => x.id === selectedId ? { ...x, ...patch } : x); remember ? commit(fn) : setLayers(fn); }, [commit, selectedId]);

  const draw = useCallback(() => {
    const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext("2d");
    ctx.clearRect(0, 0, W, H); const grad = ctx.createLinearGradient(0, 0, W, H); grad.addColorStop(0, "#21152f"); grad.addColorStop(.5, "#532d4e"); grad.addColorStop(1, "#121827"); ctx.fillStyle = grad; ctx.fillRect(0, 0, W, H);
    if (editedImage.current) ctx.drawImage(editedImage.current, 0, 0);
    else if (imageRef.current) { const img = imageRef.current, scale = Math.max(W / img.width, H / img.height), w = img.width * scale, h = img.height * scale; ctx.drawImage(img, (W - w) / 2, (H - h) / 2, w, h); }
    ctx.fillStyle = rgba(shadeColor, shade); ctx.fillRect(0, 0, W, H);
    layers.filter(x => x.visible).forEach(x => { ctx.save(); ctx.translate(x.x, x.y); ctx.rotate(x.rotation * Math.PI / 180); ctx.globalAlpha = x.opacity; ctx.font = `${x.italic ? "italic " : ""}${x.weight} ${x.size}px "${x.font}"`; ctx.textAlign = x.align; ctx.textBaseline = "middle"; ctx.fillStyle = x.color; ctx.strokeStyle = x.stroke; ctx.lineWidth = x.strokeWidth * 2; ctx.lineJoin = "round"; ctx.shadowColor = x.shadow; ctx.shadowBlur = x.shadowBlur; ctx.shadowOffsetX = x.shadowX; ctx.shadowOffsetY = x.shadowY;
      const lines = linesFor(ctx, x.text, x.maxWidth, x.spacing), lineH = x.size * x.lineHeight;
      lines.forEach((line, i) => { const y = (i - (lines.length - 1) / 2) * lineH; if (x.vertical) [...line].forEach((char, j) => drawLetters(ctx, char, 0, y + j * lineH, 0, "center")); else drawLetters(ctx, line, 0, y, x.spacing, x.align); }); ctx.restore(); });
  }, [layers, background, shade, shadeColor, imageVersion, W, H]);
  useEffect(() => draw(), [draw]);
  useEffect(() => { document.fonts?.ready?.then(() => draw()); }, [draw]);
  const fontSignature = layers.map(layer => layer.font).sort().join("|");
  useEffect(() => { let cancelled = false; const names = [...new Set(layers.map(layer => layer.font))]; Promise.allSettled(names.map(name => { const file = FONT_FILES[name]; if (!file) return document.fonts?.load?.(`48px "${name}"`) || Promise.resolve(); if (!loadedFonts.current.has(name)) { const promise = new FontFace(name, `url(/fonts/thu-phap-viet/${file})`).load().then(face => { document.fonts.add(face); return face; }); loadedFonts.current.set(name, promise); } return loadedFonts.current.get(name); })).then(() => { if (!cancelled) setImageVersion(v => v + 1); }); return () => { cancelled = true; }; }, [fontSignature]);
  const saveProject = useCallback(async (silent = false) => { try { const image = editedImage.current ? await new Promise(resolve => editedImage.current.toBlob(resolve, "image/png")) : null, now = Date.now(); await projectStore("readwrite", store => store.put({ id: "autosave", savedAt: now, formatId, layers, shade, shadeColor, background, image })); dirtyProject.current = false; setSavedAt(now); setHasSavedProject(true); if (!silent) toast.success("Đã lưu thiết kế trên thiết bị này"); } catch { if (!silent) toast.error("Không thể lưu thiết kế"); } }, [formatId, layers, shade, shadeColor, background]);
  const loadProject = async () => { try { const data = await projectStore("readonly", store => store.get("autosave")); if (!data) return toast.error("Chưa có thiết kế đã lưu. Hãy bấm Lưu trước."); dirtyProject.current = false; const next = FORMATS.find(item => item.id === data.formatId) || FORMATS[0]; if (data.image) { const url = URL.createObjectURL(data.image), img = new Image(); await new Promise((resolve, reject) => { img.onload = resolve; img.onerror = reject; img.src = url; }); const work = document.createElement("canvas"); work.width = next.width; work.height = next.height; work.getContext("2d").drawImage(img, 0, 0, work.width, work.height); editedImage.current = work; imageRef.current = img; } else { editedImage.current = null; imageRef.current = null; } setFormatId(next.id); setLayers(data.layers || []); setShade(data.shade ?? .12); setShadeColor(data.shadeColor || "#000000"); setBackground(data.background || null); setSelectedId(null); setImageVersion(v => v + 1); setSavedAt(data.savedAt); toast.success(`Đã mở bản lưu lúc ${new Date(data.savedAt).toLocaleTimeString("vi-VN")}`); } catch { toast.error("Không thể mở thiết kế đã lưu"); } };
  useEffect(() => { projectStore("readonly", store => store.get("autosave")).then(data => { setHasSavedProject(Boolean(data)); setSavedAt(data?.savedAt || null); }).catch(() => {}).finally(() => setStorageReady(true)); }, []);
  useEffect(() => { if (!storageReady || !dirtyProject.current) return; const timer = setTimeout(() => saveProject(true), 1400); return () => clearTimeout(timer); }, [saveProject, imageVersion, storageReady]);

  const addText = () => { const x = makeLayer({ text: "CHỮ MỚI", y: H * .27 + layers.length * Math.max(28, H * .028) }, { width: W, height: H }); commit(a => [...a, x]); setSelectedId(x.id); };
  const prepareBackground = (width, height, options = {}) => { if (!imageRef.current) { editedImage.current = null; return; } const zoomValue = options.zoom ?? bgZoom, xValue = options.x ?? bgX, yValue = options.y ?? bgY, brightness = options.brightness ?? bgBrightness, contrast = options.contrast ?? bgContrast, img = imageRef.current, work = document.createElement("canvas"); work.width = width; work.height = height; const ctx = work.getContext("2d"), scale = Math.max(width / img.width, height / img.height) * zoomValue, drawW = img.width * scale, drawH = img.height * scale; ctx.filter = `brightness(${brightness}%) contrast(${contrast}%)`; ctx.drawImage(img, (width - drawW) / 2 + xValue / 100 * width, (height - drawH) / 2 + yValue / 100 * height, drawW, drawH); ctx.filter = "none"; editedImage.current = work; };
  const updateBackground = patch => { dirtyProject.current=true; const next = { zoom:bgZoom, x:bgX, y:bgY, brightness:bgBrightness, contrast:bgContrast, ...patch }; if (patch.zoom != null) setBgZoom(patch.zoom); if (patch.x != null) setBgX(patch.x); if (patch.y != null) setBgY(patch.y); if (patch.brightness != null) setBgBrightness(patch.brightness); if (patch.contrast != null) setBgContrast(patch.contrast); prepareBackground(W,H,next); eraseHistory.current=[]; setCanUndoErase(false); setImageVersion(v=>v+1); };
  const changeFormat = id => { const next = FORMATS.find(item => item.id === id); if (!next || next.id === formatId) return; const scaleX = next.width / W, scaleY = next.height / H, scale = Math.min(scaleX, scaleY); commit(current => current.map(layer => ({ ...layer, x: layer.x * scaleX, y: layer.y * scaleY, size: Math.max(12, Math.round(layer.size * scale)), maxWidth: Math.min(next.width * .92, layer.maxWidth * scaleX), shadowBlur: layer.shadowBlur * scale, shadowX: layer.shadowX * scaleX, shadowY: layer.shadowY * scaleY }))); prepareBackground(next.width, next.height); eraseHistory.current = []; setCanUndoErase(false); setFormatId(id); setZoom(id === "channel" ? .24 : id === "youtube" ? .48 : .36); setImageVersion(v => v + 1); toast.success(`Đã chuyển sang ${next.name} ${next.width} × ${next.height}`); };
  const uploadImage = e => { const file = e.target.files?.[0]; if (!file) return; const url = URL.createObjectURL(file), img = new Image(); img.onload = () => { dirtyProject.current=true; imageRef.current = img; prepareBackground(W, H); eraseHistory.current = []; setCanUndoErase(false); setImageVersion(v => v + 1); setBackground(file.name); toast.success("Đã thêm ảnh nền"); }; img.onerror = () => toast.error("Không thể đọc ảnh này"); img.src = url; e.target.value = ""; };
  const uploadFont = async e => { const file = e.target.files?.[0]; if (!file) return; const name = file.name.replace(/\.[^.]+$/, ""); try { const face = new FontFace(name, `url(${URL.createObjectURL(file)})`); await face.load(); document.fonts.add(face); setCustomFonts(f => [...f, name]); update({ font: name }); toast.success(`Đã thêm font ${name}`); } catch { toast.error("Font không hợp lệ"); } e.target.value = ""; };
  const duplicate = () => { if (!selected) return; const x = { ...selected, id: uid(), x: selected.x + 35, y: selected.y + 35 }; commit(a => [...a, x]); setSelectedId(x.id); };
  const remove = () => { if (selected) { commit(a => a.filter(x => x.id !== selected.id)); setSelectedId(null); } };
  const reorder = up => commit(a => { const i = a.findIndex(x => x.id === selectedId), j = up ? Math.min(a.length - 1, i + 1) : Math.max(0, i - 1), n = [...a]; [n[i], n[j]] = [n[j], n[i]]; return n; });
  const undo = () => { if (!history.length) return; setFuture(f => [layers, ...f]); setLayers(history.at(-1)); setHistory(h => h.slice(0, -1)); };
  const redo = () => { if (!future.length) return; setHistory(h => [...h, layers]); setLayers(future[0]); setFuture(f => f.slice(1)); };
  const exportCover = type => { draw(); const a = document.createElement("a"); a.download = `${formatId === "book" ? "bia-truyen" : "youtube-cover"}-${Date.now()}.${type}`; a.href = canvasRef.current.toDataURL(`image/${type}`, .94); a.click(); toast.success(`Đã xuất ${type.toUpperCase()} ${W} × ${H} px`); };
  const point = e => { const r = canvasRef.current.getBoundingClientRect(); return { x: (e.clientX - r.left) * W / r.width, y: (e.clientY - r.top) * H / r.height }; };
  const healAt = p => { const source = editedImage.current; if (!source) return; const radius = brushSize, distance = radius * 1.55, offsets = { above:[0,-distance], below:[0,distance], left:[-distance,0], right:[distance,0] }, [ox,oy] = offsets[sampleSide]; const size = radius * 2, sx = Math.max(0, Math.min(W - size, p.x + ox - radius)), sy = Math.max(0, Math.min(H - size, p.y + oy - radius)); if (!healBrush.current) healBrush.current = document.createElement("canvas"); const patch = healBrush.current; patch.width = size; patch.height = size; const pctx = patch.getContext("2d"); pctx.clearRect(0,0,size,size); pctx.globalCompositeOperation = "source-over"; pctx.drawImage(source,sx,sy,size,size,0,0,size,size); pctx.globalCompositeOperation = "destination-in"; const feather = pctx.createRadialGradient(radius,radius,radius*.55,radius,radius,radius); feather.addColorStop(0,"rgba(0,0,0,.9)"); feather.addColorStop(1,"rgba(0,0,0,0)"); pctx.fillStyle = feather; pctx.fillRect(0,0,size,size); source.getContext("2d").drawImage(patch,p.x-radius,p.y-radius); setImageVersion(v => v + 1); };
  const undoErase = () => { const snapshot = eraseHistory.current.pop(); if (!snapshot || !editedImage.current) return; editedImage.current.getContext("2d").putImageData(snapshot,0,0); setCanUndoErase(eraseHistory.current.length > 0); setImageVersion(v => v + 1); toast.success("Đã hoàn tác nét xóa"); };
  const findLayer = p => [...layers].reverse().find(x => { if (!x.visible) return false; const rows = x.text.split("\n"), longest = Math.max(1, ...rows.map(line => line.length)); const halfW = x.vertical ? x.size : Math.min(x.maxWidth, Math.max(x.size * 1.2, longest * x.size * .72)) / 2; const halfH = x.vertical ? Math.min(H, longest * x.size * x.lineHeight) / 2 : Math.max(x.size, rows.length * x.size * x.lineHeight) / 2; const rad = -x.rotation * Math.PI / 180, dx = p.x - x.x, dy = p.y - x.y; return Math.abs(dx * Math.cos(rad) - dy * Math.sin(rad)) <= halfW + 35 && Math.abs(dx * Math.sin(rad) + dy * Math.cos(rad)) <= halfH + 30; });
  const focusEditor = (selectAll = false) => requestAnimationFrame(() => { textInput.current?.focus(); if (selectAll) textInput.current?.select(); });
  const pointerDown = e => { const p = point(e); if (eraseMode) { if (!editedImage.current) return toast.error("Hãy tải ảnh nền trước"); canvasRef.current.setPointerCapture(e.pointerId); eraseHistory.current.push(editedImage.current.getContext("2d").getImageData(0,0,W,H)); if (eraseHistory.current.length > 5) eraseHistory.current.shift(); setCanUndoErase(true); drag.current = { erase:true }; healAt(p); return; } const hit = findLayer(p); setSelectedId(hit?.id || null); if (hit) { canvasRef.current.setPointerCapture(e.pointerId); drag.current = { id: hit.id, dx: p.x - hit.x, dy: p.y - hit.y, startX: p.x, startY: p.y, moved: false, before: layers }; } };
  const pointerMove = e => { const active = drag.current; if (!active) return; const p = point(e); if (active.erase) { healAt(p); return; } if (Math.hypot(p.x - active.startX, p.y - active.startY) > 5) active.moved = true; if (!active.moved) return; let nextX = Math.max(0, Math.min(W, p.x - active.dx)), nextY = Math.max(0, Math.min(H, p.y - active.dy)); const snap = Math.max(14, Math.min(W,H) * .015), snapX = Math.abs(nextX - W / 2) < snap, snapY = Math.abs(nextY - H / 2) < snap; if (snapX) nextX = W / 2; if (snapY) nextY = H / 2; setGuides({ x:snapX, y:snapY }); const layerId = active.id; setLayers(a => a.map(x => x.id === layerId ? { ...x, x: nextX, y: nextY } : x)); };
  const pointerUp = () => { const completed = drag.current; if (!completed) return; drag.current = null; setGuides({x:false,y:false}); if (completed.erase) return; if (completed.moved) { const previousLayers = completed.before; setHistory(h => [...h.slice(-29), previousLayers]); setFuture([]); } else focusEditor(false); };
  const doubleClick = e => { const hit = findLayer(point(e)); if (hit) { setSelectedId(hit.id); focusEditor(true); } };
  const resizeDown = e => { if (!selected) return; e.stopPropagation(); e.currentTarget.setPointerCapture(e.pointerId); drag.current = { resize:true, startX:e.clientX, startSize:selected.size, startWidth:selected.maxWidth, before:layers }; };
  const resizeMove = e => { const active=drag.current; if (!active?.resize) return; const delta=(e.clientX-active.startX)/zoom, ratio=Math.max(.2,(active.startSize+delta)/active.startSize); setLayers(current=>current.map(layer=>layer.id===selectedId?{...layer,size:Math.max(12,Math.min(400,active.startSize*ratio)),maxWidth:Math.max(160,Math.min(W*.95,active.startWidth*ratio))}:layer)); };
  const resizeUp = () => { const active=drag.current; if (!active?.resize) return; drag.current=null; setHistory(h=>[...h.slice(-29),active.before]); setFuture([]); };
  const rotateDown = e => { if (!selected) return; e.stopPropagation(); e.currentTarget.setPointerCapture(e.pointerId); const rect=canvasRef.current.getBoundingClientRect(); drag.current={rotate:true,cx:rect.left+selected.x/W*rect.width,cy:rect.top+selected.y/H*rect.height,before:layers}; };
  const rotateMove = e => { const active=drag.current; if (!active?.rotate) return; const angle=Math.atan2(e.clientY-active.cy,e.clientX-active.cx)*180/Math.PI+90; setLayers(current=>current.map(layer=>layer.id===selectedId?{...layer,rotation:Math.round(angle)}:layer)); };
  const rotateUp = () => { const active=drag.current; if (!active?.rotate) return; drag.current=null; setHistory(h=>[...h.slice(-29),active.before]); setFuture([]); };
  const applyPreset = preset => { if (selected) { update(preset.style); return; } const layer = makeLayer({ text: preset.name.toUpperCase(), ...preset.style }); commit(a => [...a, layer]); setSelectedId(layer.id); };

  return <div className="cover-studio">
    <header className="cover-toolbar"><div className="cover-toolbar-group"><button className="cover-icon-btn" onClick={() => navigate("/")}><ArrowLeft /></button><div className="cover-brand"><span><Palette /></span><div><strong>Studio Bìa Truyện</strong><small>Thiết kế bìa chuyên nghiệp</small></div></div></div><div className="cover-toolbar-group"><button className="cover-icon-btn" onClick={undo} disabled={!history.length}><Undo2 /></button><button className="cover-icon-btn" onClick={redo} disabled={!future.length}><Redo2 /></button><i className="cover-divider"/><button className="cover-icon-btn" onClick={loadProject} title="Mở thiết kế gần nhất"><FolderOpen /></button><button className="cover-icon-btn" onClick={() => saveProject(false)} title="Lưu thiết kế"><Save /></button><button className="cover-export" onClick={() => exportCover("png")}><Download /> Xuất PNG</button></div></header>
    <div className="cover-layout">
      <aside className="cover-sidebar cover-sidebar--left">
        <section><h3>Định dạng thiết kế</h3><div className="cover-format-list">{FORMATS.map(item => <button key={item.id} className={formatId === item.id ? "active" : ""} onClick={() => changeFormat(item.id)}><span className={`cover-format-icon ${item.id === "book" ? "portrait" : "landscape"}`}/><span><strong>{item.name}</strong><small>{item.width} × {item.height} · {item.hint}</small></span></button>)}</div>{formatId !== "book" && <label className="cover-safe-toggle"><input type="checkbox" checked={showSafeZone} onChange={e => setShowSafeZone(e.target.checked)}/> Hiện vùng an toàn YouTube</label>}{savedAt && <small className="cover-autosave">Đã tự lưu lúc {new Date(savedAt).toLocaleTimeString("vi-VN", {hour:"2-digit",minute:"2-digit"})}</small>}</section>
        <section><h3>Ảnh nền</h3><button className="cover-upload" onClick={() => imageInput.current.click()}><ImagePlus/><span><strong>{background ? "Đổi ảnh nền" : "Tải ảnh của bạn"}</strong><small>{background || "JPG, PNG, WEBP · tự căn đầy bìa"}</small></span></button><input ref={imageInput} hidden type="file" accept="image/*" onChange={uploadImage}/>{background && <details className="cover-bg-controls"><summary>Điều chỉnh ảnh nền</summary><Range label="Phóng to" value={Math.round(bgZoom*100)} min={100} max={220} suffix="%" onChange={v=>updateBackground({zoom:v/100})}/><Range label="Di chuyển ngang" value={bgX} min={-50} max={50} onChange={v=>updateBackground({x:v})}/><Range label="Di chuyển dọc" value={bgY} min={-50} max={50} onChange={v=>updateBackground({y:v})}/><Range label="Độ sáng" value={bgBrightness} min={40} max={160} suffix="%" onChange={v=>updateBackground({brightness:v})}/><Range label="Tương phản" value={bgContrast} min={40} max={180} suffix="%" onChange={v=>updateBackground({contrast:v})}/><small>Mỗi thay đổi ảnh nền sẽ làm mới lịch sử cọ xóa.</small></details>}</section>
        <section><div className="cover-section-title"><h3>Xóa chữ có sẵn</h3><span className="cover-free-badge">FREE</span></div><button className={`cover-erase-toggle ${eraseMode ? "active" : ""}`} onClick={() => setEraseMode(v => !v)}><Brush/><span><strong>{eraseMode ? "Đang bật cọ xóa" : "Bật cọ xóa chữ"}</strong><small>Tô lên chữ để vá bằng vùng nền gần đó</small></span></button>{eraseMode && <div className="cover-erase-options"><Range label="Kích thước cọ" value={brushSize} min={18} max={140} onChange={setBrushSize}/><label className="cover-erase-source"><span>Lấy mẫu nền từ</span><select value={sampleSide} onChange={e => setSampleSide(e.target.value)}><option value="above">Phía trên</option><option value="below">Phía dưới</option><option value="left">Bên trái</option><option value="right">Bên phải</option></select></label><button className="cover-undo-erase" disabled={!canUndoErase} onClick={undoErase}><Undo2/> Hoàn tác nét xóa</button><small className="cover-erase-tip">Mẹo: dùng cọ nhỏ, quét nhiều nét ngắn và đổi hướng lấy mẫu khi nền không khớp.</small></div>}</section>
        <section><div className="cover-section-title"><h3>Lớp chữ</h3><button onClick={addText}><Plus/> Thêm chữ</button></div><div className="cover-layer-list">{[...layers].reverse().map(x => <button key={x.id} className={selectedId === x.id ? "active" : ""} onClick={() => setSelectedId(x.id)}><Type/><span>{x.text || "Chưa có nội dung"}</span><i onClick={e => { e.stopPropagation(); commit(a => a.map(v => v.id === x.id ? { ...v, visible: !v.visible } : v)); }}>{x.visible ? <Eye/> : <EyeOff/>}</i></button>)}</div></section>
        <section><h3>Phong cách nhanh</h3><div className="cover-presets">{PRESETS.map(p => <button key={p.name} style={{fontFamily:p.style.font,color:p.style.color,textShadow:`0 2px 5px ${p.style.shadow}`}} onClick={() => applyPreset(p)}>{p.name}</button>)}</div><small className="cover-preset-tip">Chọn chữ rồi bấm một phong cách, hoặc bấm để tự tạo lớp chữ mới.</small></section>
        <section><h3>Lớp phủ ảnh</h3><label className="cover-field"><span>Màu phủ<input type="color" value={shadeColor} onChange={e => setShadeColor(e.target.value)}/></span><input type="range" min="0" max=".8" step=".01" value={shade} onChange={e => setShade(+e.target.value)}/></label></section>
      </aside>
      <main className="cover-stage-wrap"><div className="cover-stage-scroll">{!background && <div className="cover-empty-hint"><Upload/><strong>Bắt đầu với ảnh của bạn</strong><span>Tải ảnh ở thanh bên trái, sau đó kéo chữ trực tiếp trên bìa</span></div>}<div className={`cover-canvas-frame ${eraseMode ? "is-erasing" : ""}`} style={{width:W*zoom,height:H*zoom}}><canvas ref={canvasRef} width={W} height={H} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} onDoubleClick={doubleClick}/>{showSafeZone && formatId !== "book" && <div className={`cover-safe-zone ${formatId}`}>{formatId === "channel" && <span>Vùng an toàn mọi thiết bị</span>}</div>}{guides.x && <i className="cover-guide cover-guide--x"/>}{guides.y && <i className="cover-guide cover-guide--y"/>}{selected?.visible && !eraseMode && <div className="cover-selection" style={{left:`${selected.x/W*100}%`,top:`${selected.y/H*100}%`,width:`${Math.min(selected.maxWidth+80,W)/W*100}%`,height:`${Math.max(selected.size*1.45,100)/H*100}%`,transform:`translate(-50%,-50%) rotate(${selected.rotation}deg)`}}><b onPointerDown={rotateDown} onPointerMove={rotateMove} onPointerUp={rotateUp}/><span onPointerDown={resizeDown} onPointerMove={resizeMove} onPointerUp={resizeUp}/></div>}</div></div><div className="cover-zoom"><button onClick={() => setZoom(z => Math.max(.18,z-.04))}><ZoomOut/></button><span>{Math.round(zoom*100)}%</span><button onClick={() => setZoom(z => Math.min(.7,z+.04))}><ZoomIn/></button></div></main>
      <aside className="cover-sidebar cover-sidebar--right">{!selected ? <div className="cover-no-selection"><Type/><strong>Chọn một lớp chữ</strong><span>Nhấp vào chữ trên bìa hoặc trong danh sách để chỉnh sửa.</span></div> : <>
        <section><h3>Nội dung</h3><textarea ref={textInput} className="cover-textarea" value={selected.text} onChange={e => update({text:e.target.value},false)} rows="4" placeholder="Nhập tiêu đề truyện..."/><small className="cover-edit-tip">Giữ chuột để kéo · nhấp để sửa · nhấp đúp để thay toàn bộ</small></section>
        <section><h3>Kiểu chữ</h3><select className="cover-select" value={selected.font} onChange={e => update({font:e.target.value})}><optgroup label="Thư pháp Việt · Unicode">{CURATED_FONTS.map(([f]) => <option key={f} value={f}>{f}</option>)}</optgroup><optgroup label="Font mã VNI cũ · có thể lỗi dấu">{ARCHIVE_FONTS.map(([f]) => <option key={f} value={f}>⚠ {f}</option>)}</optgroup><optgroup label="Font phổ thông">{FONTS.filter(f => !LOCAL_FONTS.some(([name]) => name === f)).map(f => <option key={f} value={f}>{f}</option>)}</optgroup>{customFonts.length > 0 && <optgroup label="Font của bạn">{customFonts.map(f => <option key={f} value={f}>{f}</option>)}</optgroup>}</select><div className="cover-current-font" style={{fontFamily:selected.font}}>Truyện Kiều · Nguyễn Du</div><small className="cover-font-saving">Tiết kiệm dữ liệu: chỉ font bạn chọn mới được tải.</small><details className="cover-font-gallery" open><summary>{CURATED_FONTS.length} font Unicode dùng tốt</summary><div>{CURATED_FONTS.map(([font]) => <button key={font} className={selected.font===font?"active":""} onClick={() => update({font})}><span>Chọn font</span><small>{font}</small></button>)}</div></details><details className="cover-font-gallery cover-font-gallery--legacy"><summary>{ARCHIVE_FONTS.length} font mã cũ · có thể lỗi dấu</summary><p>Nhóm này được giữ theo yêu cầu nhưng không đảm bảo nhập Unicode trực tiếp.</p><div>{ARCHIVE_FONTS.map(([font]) => <button key={font} className={selected.font===font?"active":""} onClick={() => update({font})}><span>Chọn font</span><small>{font}</small></button>)}</div></details><button className="cover-font-upload" onClick={() => fontInput.current.click()}><Upload/> Tải font riêng (.ttf, .otf)</button><input ref={fontInput} hidden type="file" accept=".ttf,.otf,.woff,.woff2" onChange={uploadFont}/><div className="cover-inline"><label>Cỡ chữ<input type="number" min="12" max="400" value={selected.size} onChange={e => update({size:+e.target.value},false)}/></label><label>Độ đậm<select value={selected.weight} onChange={e => update({weight:+e.target.value})}><option value="400">Thường</option><option value="600">Đậm vừa</option><option value="700">Đậm</option><option value="900">Rất đậm</option></select></label></div><div className="cover-button-row"><button className={selected.weight>=700?"active":""} onClick={() => update({weight:selected.weight>=700?400:700})}><Bold/></button><button className={selected.italic?"active":""} onClick={() => update({italic:!selected.italic})}><Italic/></button>{[AlignLeft,AlignCenter,AlignRight].map((Icon,i)=>{const v=["left","center","right"][i];return <button key={v} className={selected.align===v?"active":""} onClick={()=>update({align:v})}><Icon/></button>})}<button className={selected.vertical?"active":""} onClick={()=>update({vertical:!selected.vertical})}><b className="vertical-glyph">DỌC</b></button></div></section>
        <section><h3>Màu & hiệu ứng</h3><div className="cover-colors"><Color label="Màu chữ" value={selected.color} onChange={v=>update({color:v},false)}/><Color label="Màu viền" value={selected.stroke} onChange={v=>update({stroke:v},false)}/><Color label="Màu bóng" value={selected.shadow} onChange={v=>update({shadow:v},false)}/></div><Range label="Độ dày viền" value={selected.strokeWidth} min={0} max={18} onChange={v=>update({strokeWidth:v},false)}/><Range label="Độ mờ bóng" value={selected.shadowBlur} min={0} max={60} onChange={v=>update({shadowBlur:v},false)}/><Range label="Độ trong suốt" value={Math.round(selected.opacity*100)} min={10} max={100} suffix="%" onChange={v=>update({opacity:v/100},false)}/></section>
        <section><h3>Bố cục</h3><Range label="Xoay" value={selected.rotation} min={-180} max={180} suffix="°" onChange={v=>update({rotation:v},false)}/><Range label="Khoảng cách chữ" value={selected.spacing} min={-5} max={40} onChange={v=>update({spacing:v},false)}/><Range label="Khung chữ" value={selected.maxWidth} min={200} max={1100} onChange={v=>update({maxWidth:v},false)}/><div className="cover-actions"><button onClick={duplicate}><Copy/> Nhân bản</button><button onClick={()=>reorder(true)}><ArrowUp/> Lên trên</button><button onClick={()=>reorder(false)}><ArrowDown/> Xuống dưới</button><button className="danger" onClick={remove}><Trash2/> Xóa</button></div></section>
      </>}</aside>
    </div>
  </div>;
}
function Range({label,value,min,max,suffix="",onChange}) { return <label className="cover-field"><span>{label}<b>{value}{suffix}</b></span><input type="range" min={min} max={max} value={value} onChange={e=>onChange(+e.target.value)}/></label>; }
function Color({label,value,onChange}) { return <label><span>{label}</span><input type="color" value={value} onChange={e=>onChange(e.target.value)}/></label>; }
